<?php

namespace BehatViewer\BehatViewerBundle\Entity\Repository;

use BehatViewer\BehatViewerBundle\Entity;

/**
 * BuildStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureStatRepository extends EntityRepository
{
}
