<?php

namespace BehatViewer\BehatViewerBundle\Entity\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function loadUserByUsername($username)
	{
		$q = $this
			->createQueryBuilder('u')
			->select('u, g')
			->leftJoin('u.groups', 'g')
			->where('u.username = :username OR u.email = :email')
			->setParameter('username', $username)
			->setParameter('email', $username)
			->getQuery();

		return $q->getResult();
	}
}
