<?php

namespace BehatViewer\BehatViewerWorkerBundle\Entity\Repository;

use BehatViewer\BehatViewerBundle\Entity;
use BehatViewer\BehatViewerBundle\Entity\Repository\EntityRepository;

/**
 * BuildStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
}
