<?php

namespace BehatViewer\BehatViewerCoreBundle\Entity\Repository;

use Doctrine\ORM\Query\Expr,
    BehatViewer\BehatViewerCoreBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
}
