<?php

namespace jubianchi\BehatViewerBundle\Entity\Repository;

use jubianchi\BehatViewerBundle\Entity;

/**
 * BuildStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildStatRepository extends EntityRepository
{
}
