<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120903195721 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE behatviewer_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(30) NOT NULL, role VARCHAR(20) NOT NULL, UNIQUE INDEX UNIQ_B040191A57698A6A (role), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE behatviewer_user_role (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_5D6C7062A76ED395 (user_id), INDEX IDX_5D6C7062D60322AC (role_id), PRIMARY KEY(user_id, role_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE behatviewer_user_role ADD CONSTRAINT FK_5D6C7062A76ED395 FOREIGN KEY (user_id) REFERENCES behatviewer_user (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE behatviewer_user_role ADD CONSTRAINT FK_5D6C7062D60322AC FOREIGN KEY (role_id) REFERENCES behatviewer_role (id) ON DELETE CASCADE");

		$this->addSql("INSERT INTO behatviewer_role VALUES (1, 'User', 'ROLE_USER'), (2, 'Admin', 'ROLE_ADMIN')");
		$this->addSql("INSERT INTO behatviewer_user_role SELECT id, 1 FROM behatviewer_user");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE behatviewer_user_role DROP FOREIGN KEY FK_5D6C7062D60322AC");
        $this->addSql("DROP TABLE behatviewer_role");
        $this->addSql("DROP TABLE behatviewer_user_role");
    }
}
