<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120906222655 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE behatviewer_build CHANGE status status ENUM('passed', 'failed') NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_feature CHANGE status status ENUM('passed', 'failed') NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_project CHANGE type type ENUM('public', 'private') DEFAULT 'public' NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_scenario CHANGE status status ENUM('passed', 'failed') NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_step CHANGE status status ENUM('passed', 'failed', 'skipped', 'pending', 'undefined') NOT NULL");
        $this->addSql("ALTER TABLE acl_classes CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL");
        $this->addSql("ALTER TABLE acl_security_identities CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL");
        $this->addSql("ALTER TABLE acl_object_identities CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE parent_object_identity_id parent_object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE class_id class_id INT UNSIGNED NOT NULL");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors CHANGE object_identity_id object_identity_id INT UNSIGNED NOT NULL, CHANGE ancestor_id ancestor_id INT UNSIGNED NOT NULL");
        $this->addSql("ALTER TABLE acl_entries CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE object_identity_id object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE security_identity_id security_identity_id INT UNSIGNED NOT NULL, CHANGE class_id class_id INT UNSIGNED NOT NULL, CHANGE ace_order ace_order SMALLINT UNSIGNED NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE acl_classes CHANGE id id INT AUTO_INCREMENT NOT NULL");
        $this->addSql("ALTER TABLE acl_entries CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE class_id class_id INT NOT NULL, CHANGE object_identity_id object_identity_id INT DEFAULT NULL, CHANGE security_identity_id security_identity_id INT NOT NULL, CHANGE ace_order ace_order SMALLINT NOT NULL");
        $this->addSql("ALTER TABLE acl_object_identities CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE parent_object_identity_id parent_object_identity_id INT DEFAULT NULL, CHANGE class_id class_id INT NOT NULL");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors CHANGE object_identity_id object_identity_id INT NOT NULL, CHANGE ancestor_id ancestor_id INT NOT NULL");
        $this->addSql("ALTER TABLE acl_security_identities CHANGE id id INT AUTO_INCREMENT NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_build CHANGE status status VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_feature CHANGE status status VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_project CHANGE type type VARCHAR(255) DEFAULT 'public' NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_scenario CHANGE status status VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE behatviewer_step CHANGE status status VARCHAR(255) NOT NULL");
    }
}
